# Generated by Django 5.2.14 on 2026-06-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='pid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
