# Generated by Django 5.2.14 on 2026-06-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_scantask_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkTamper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='框架标识名，如 django, express', max_length=50, unique=True)),
                ('language', models.CharField(help_text='语言，如 python, javascript', max_length=20)),
                ('framework_name', models.CharField(default='', help_text='显示名称，如 Django, Express', max_length=50)),
                ('dependencies', models.JSONField(blank=True, default=dict, help_text='DEPENDENCIES dict')),
                ('filter_functions', models.JSONField(blank=True, default=dict, help_text='FILTER_FUNCTIONS dict')),
                ('extra_sinks', models.JSONField(blank=True, default=list, help_text='EXTRA_SINKS list')),
                ('controlled_sources', models.JSONField(blank=True, default=list, help_text='CONTROLLED_SOURCES list')),
                ('detect_code', models.TextField(blank=True, default='', help_text='detect() 函数源码')),
            ],
            options={
                'verbose_name': 'Framework Tamper',
                'db_table': 'framework_tamper',
            },
        ),
        migrations.DeleteModel(
            name='Tampers',
        ),
    ]
